# Generated by Django 5.2.1 on 2025-06-14 02:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha_postulacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion.perro')),
            ],
        ),
    ]
