# Generated by Django 5.2.1 on 2025-06-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_postulacionadopcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='vacunado',
        ),
        migrations.AddField(
            model_name='usuarioadoptante',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='peso',
            field=models.FloatField(default=0.0),
        ),
    ]
