# Generated by Django 5.2.1 on 2025-06-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_remove_perro_vacunado_usuarioadoptante_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
